services:
  mongo:
    image: "mongo"
    ports:
      - "8080:27017"
    networks:
      - devops-mern-network
  
  backend:
    build: ./backend
    ports:
      - "5005:5005"
    env_file:
      - ./backend/.env.prod
    depends_on:
      - mongo
    networks:
      - devops-mern-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env.prod
    depends_on:
      - backend
    networks:
      - devops-mern-network

networks:
  devops-mern-network:
    driver: bridge
    
