name: MERN CI
on:
  push:
    branches: [ main ]

jobs:
  mongo-init:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports: ['27017:27017']

    steps:

      - name: checkout repo
        uses: actions/checkout@v7

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: init mongoDB
        run: |
          until nc -z localhost:27017; do
            echo "waiting for mongo connection.."
            sleep 2
          done
            echo "mongoDB connected"

      - name: Seed data's
        working-directory: ./backend
        run: |
          npm install
          node seedTasksData.js
  
  run-test:
    runs-on: ubuntu-latest
    needs: mongo-init

    env:
      PORT: ${{ secrets.PORT }}
      MONGO_URI: ${{ secrets.MONGO_URI }}


    steps:
      - name: checkout repo
        uses: actions/checkout@v7

      - name: setup node js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: install dependancies
        working-directory: ./backend
        run: npm install

      - name: run tests
        working-directory: ./backend
        run: npm run test
      